### ISSUE TITLE
window下pycharm中安装opencv-python后无法使用

### ISSUE THREAD

**Issue by ghost** [moneyDboat/wechat_jump_jump#2]
Traceback (most recent call last):
  File "D:/Workspaces/PythonProjects/testjwxt/jump.py", line 2, in <module>
    import cv2
  File "D:\Workspaces\PythonProjects\testjwxt\venv\lib\site-packages\cv2\__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: DLL load failed: 找不到指定的模块。

**Comment by moneyDboat** [comment]
你试试在命令行中python能不能import cv2，我觉得可能是Pycharm的Python环境没配置好

**Comment by Darkxiete** [comment]
python3.dll文件缺失 自己去下载一个复制就行

**Comment by AbdielNie** [comment]
Traceback (most recent call last):
  File "E:/demo/main.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
那这样的错误呢

**Comment by moneyDboat** [comment]
opencv-python模块没装好
试试pip install opencv-python
